services:
  datastore:
    ports:
      - "127.0.0.1:${POSTGRES_DEV_PORT:-18883}:5432"

  solax_reader:
    volumes:
      - ./solax_reader/src:/app:ro

  azrouter_reader:
    volumes:
      - ./azrouter_reader/src:/app:ro

  solar_forecast_reader:
    volumes:
      - ./solar_forecast_reader/src:/app:ro

  reporter:
    volumes:
      - ./reporter/src:/app:ro

  telemetry_api:
    ports:
      - "127.0.0.1:${TELEMETRY_API_DEV_PORT:-18881}:8000"
    volumes:
      - ./telemetry_api/src:/app:ro

  controller:
    ports:
      - "127.0.0.1:${CONTROLLER_DEV_PORT:-18882}:${CONTROLLER_PORT:-8090}"
    volumes:
      - ./controller/src:/app:ro

  ui:
    ports:
      - "127.0.0.1:${UI_PORT:-18880}:80"
    volumes:
      - ./ui/src:/usr/share/nginx/html:ro
